"""Add Neo4j status fields

Revision ID: 85ddc4257fc7
Revises: c68e2ab2faaa
Create Date: 2026-07-27 07:39:27.746692+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = '85ddc4257fc7'
down_revision: Union[str, None] = 'c68e2ab2faaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               comment='Unique conversation identifier.',
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner user reference.',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=300),
               comment='Conversation title — may be auto-generated.',
               existing_nullable=False,
               existing_server_default=sa.text("'New Conversation'::character varying"))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of conversation creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last activity.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_metadata', 'id',
               existing_type=sa.UUID(),
               comment='Unique metadata record identifier.',
               existing_nullable=False)
    op.alter_column('document_metadata', 'document_id',
               existing_type=sa.UUID(),
               comment='Parent document reference (one-to-one).',
               existing_nullable=False)
    op.alter_column('document_metadata', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='Extracted or user-provided document title.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment='Detected document language (ISO 639-1 code).',
               existing_nullable=True)
    op.alter_column('document_metadata', 'page_count',
               existing_type=sa.INTEGER(),
               comment='Number of pages in the document.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'chunk_count',
               existing_type=sa.INTEGER(),
               comment='Number of text chunks produced by the AI pipeline.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of metadata creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('document_metadata_document_id_key', 'document_metadata', type_='unique')
    op.drop_index('ix_document_metadata_document_id', table_name='document_metadata')
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=True)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               comment='Unique document identifier.',
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner user reference.',
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=500),
               comment='Original uploaded filename.',
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment="MIME type or file extension (e.g. 'application/pdf').",
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes.',
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.TEXT(),
               comment='Object storage path (MinIO key).',
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status'),
               comment='Current processing status.',
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::document_status"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of document upload.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last status change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment='Unique message identifier.',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               comment='Parent conversation reference.',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', name='message_role'),
               comment='Message author role (USER or ASSISTANT).',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Message text content.',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of message creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'id',
               existing_type=sa.UUID(),
               comment='Unique setting identifier.',
               existing_nullable=False)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment='Setting key — must be unique.',
               existing_nullable=False)
    op.alter_column('system_settings', 'value',
               existing_type=sa.TEXT(),
               comment='Setting value (stored as text).',
               existing_nullable=False)
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of setting creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last value change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('system_settings_key_key', 'system_settings', type_='unique')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Unique user identifier.',
               existing_nullable=False)
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Supabase Auth user ID (auth.users.id).',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address — must be unique.',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment='Display username — must be unique.',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Application role: USER or ADMIN.',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user account is active.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of account creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last account update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last account update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of account creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user account is active.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Application role: USER or ADMIN.',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display username — must be unique.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User email address — must be unique.',
               existing_nullable=False)
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Supabase Auth user ID (auth.users.id).',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique user identifier.',
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_unique_constraint('system_settings_key_key', 'system_settings', ['key'])
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last value change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of setting creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Setting value (stored as text).',
               existing_nullable=False)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Setting key — must be unique.',
               existing_nullable=False)
    op.alter_column('system_settings', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique setting identifier.',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of message creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Message text content.',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', name='message_role'),
               comment=None,
               existing_comment='Message author role (USER or ASSISTANT).',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Parent conversation reference.',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique message identifier.',
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last status change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of document upload.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status'),
               comment=None,
               existing_comment='Current processing status.',
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::document_status"))
    op.alter_column('documents', 'storage_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Object storage path (MinIO key).',
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes.',
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="MIME type or file extension (e.g. 'application/pdf').",
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Original uploaded filename.',
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user reference.',
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique document identifier.',
               existing_nullable=False)
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.create_index('ix_document_metadata_document_id', 'document_metadata', ['document_id'], unique=False)
    op.create_unique_constraint('document_metadata_document_id_key', 'document_metadata', ['document_id'])
    op.alter_column('document_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of metadata creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_metadata', 'chunk_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of text chunks produced by the AI pipeline.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'page_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of pages in the document.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Detected document language (ISO 639-1 code).',
               existing_nullable=True)
    op.alter_column('document_metadata', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Extracted or user-provided document title.',
               existing_nullable=True)
    op.alter_column('document_metadata', 'document_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Parent document reference (one-to-one).',
               existing_nullable=False)
    op.alter_column('document_metadata', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique metadata record identifier.',
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last activity.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of conversation creation.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Conversation title — may be auto-generated.',
               existing_nullable=False,
               existing_server_default=sa.text("'New Conversation'::character varying"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user reference.',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique conversation identifier.',
               existing_nullable=False)
    # ### end Alembic commands ###
