"""Add Workspace model and relations

Revision ID: 98112526d163
Revises: 78ff050d6269
Create Date: 2026-07-28 06:50:49.576083+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = '98112526d163'
down_revision: Union[str, None] = '78ff050d6269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique workspace identifier.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user reference.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the workspace/project.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the workspace.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of workspace creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('workspace_id', sa.UUID(), nullable=True, comment='Parent workspace reference.'))
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), nullable=True, comment='Parent workspace reference.'))
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_column('documents', 'workspace_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_column('conversations', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
