"""Sync model fixes

Revision ID: 78ff050d6269
Revises: 85ddc4257fc7
Create Date: 2026-07-27 07:54:38.904300+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = '78ff050d6269'
down_revision: Union[str, None] = '85ddc4257fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('extraction_version', sa.String(length=50), nullable=True, comment='Version of the extraction prompt/model used.'))
    op.add_column('document_chunks', sa.Column('graph_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the chunk was successfully synced to Neo4j.'))

    op.execute("CREATE TYPE graph_extraction_status AS ENUM ('PENDING', 'EXTRACTING', 'COMPLETED', 'FAILED')")
    op.execute("CREATE TYPE graph_sync_status AS ENUM ('PENDING', 'SYNCING', 'COMPLETED', 'FAILED')")

    op.execute("ALTER TABLE document_chunks ALTER COLUMN entity_extraction_status DROP DEFAULT")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN entity_extraction_status TYPE graph_extraction_status USING entity_extraction_status::text::graph_extraction_status")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN entity_extraction_status SET DEFAULT 'PENDING'::graph_extraction_status")

    op.execute("ALTER TABLE document_chunks ALTER COLUMN graph_sync_status DROP DEFAULT")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN graph_sync_status TYPE graph_sync_status USING graph_sync_status::text::graph_sync_status")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN graph_sync_status SET DEFAULT 'PENDING'::graph_sync_status")

    op.execute("DROP TYPE entity_extraction_status_enum")
    op.execute("DROP TYPE graph_sync_status_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'graph_sync_status',
               existing_type=sa.Enum('PENDING', 'SYNCING', 'COMPLETED', 'FAILED', name='graph_sync_status', create_constraint=True),
               type_=postgresql.ENUM('PENDING', 'SYNCED', 'FAILED', name='graph_sync_status_enum'),
               existing_comment='Status of synchronization to Neo4j knowledge graph.',
               existing_nullable=False)
    op.alter_column('document_chunks', 'entity_extraction_status',
               existing_type=sa.Enum('PENDING', 'EXTRACTING', 'COMPLETED', 'FAILED', name='graph_extraction_status', create_constraint=True),
               type_=postgresql.ENUM('PENDING', 'EXTRACTING', 'COMPLETED', 'FAILED', name='entity_extraction_status_enum'),
               existing_comment='Status of entity/relationship extraction from this chunk.',
               existing_nullable=False)
    op.drop_column('document_chunks', 'graph_updated_at')
    op.drop_column('document_chunks', 'extraction_version')
    # ### end Alembic commands ###
