"""Add embedding versioning metadata

Revision ID: c68e2ab2faaa
Revises: 361eae9fd985
Create Date: 2026-07-27 07:30:55.962136+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = 'c68e2ab2faaa'
down_revision: Union[str, None] = '361eae9fd985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_dimension', sa.Integer(), nullable=True, comment='Dimension of the embedding vector.'))
    op.add_column('document_chunks', sa.Column('embedding_version', sa.String(length=50), nullable=True, comment='Version of the embedding model used.'))
    op.add_column('document_chunks', sa.Column('vector_generated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the vector embedding was generated.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'vector_generated_at')
    op.drop_column('document_chunks', 'embedding_version')
    op.drop_column('document_chunks', 'embedding_dimension')
    # ### end Alembic commands ###
