"""Add TTS fields to message

Revision ID: 6d1e33c7192e
Revises: 98112526d163
Create Date: 2026-07-29 15:44:58.200609+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = '6d1e33c7192e'
down_revision: Union[str, None] = '98112526d163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_storage_path', sa.String(length=500), nullable=True, comment='MinIO object key for generated TTS audio.'))
    op.add_column('messages', sa.Column('audio_language', sa.String(length=10), nullable=True, comment='Language of the currently cached audio.'))
    op.add_column('messages', sa.Column('audio_generated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when audio was generated.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'audio_generated_at')
    op.drop_column('messages', 'audio_language')
    op.drop_column('messages', 'audio_storage_path')
    # ### end Alembic commands ###
